### PR TITLE
Put the navbar html code into it's own template.

### PR DESCRIPTION
**Pull request by Davo36**
Menno, this works, but the html files are not packaged into the binary. Which they haven't been up until now.

Not sure how to package them up using packr and then still access them with the ParseGlob function at the top of management-interface.go

### CODE REVIEW

**Comment by Davo36** [comment]
Menno, I have tested this now... (after making the second commit haha).  It's working on Windows... I ran it from my desktop no problem.  But it's not working on the Rasp Pi.

I did a packr clean, then rebuilt it.  I use: env GOOS=linux GOARCH=arm GOARM=7 packr build.  

And when testing on the Rasp Pi, I get blank pages...  not the "404 page not found" error, just a blank page.  I'll look into it.

**Comment by Davo36** [comment]
Menno, it's a packr issue: https://github.com/gobuffalo/packr/issues/75

Interestingly a guy mentions having this issue with the raspberry pi.  Only a few days ago too.

**Comment by mjs** [comment]
I'll take a look. Failing that, apparently https://github.com/rakyll/statik is a similar thing to packr which does work with the Pi.

**Comment by Davo36** [comment]
Yeah, I might give it a try.

**Pull request merged**
